# Generated by Django 5.1.6 on 2025-02-16 16:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_house_state'),
        ('HouseRentManagementApp', '0004_userprofile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='AdminApp.house'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='HouseRentManagementApp.userprofile'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_no',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='image1',
            field=models.ImageField(upload_to='house_images/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image2',
            field=models.ImageField(upload_to='house_images/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='pincode',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='house',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses_owned', to='HouseRentManagementApp.userprofile'),
        ),
        migrations.CreateModel(
            name='HelpDeskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='AdminApp.house')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_queries_received', to='HouseRentManagementApp.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='HouseRentManagementApp.userprofile')),
            ],
        ),
    ]
