# Generated by Django 5.1.6 on 2025-03-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='house_images/'),
        ),
        migrations.AddField(
            model_name='house',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='house_images/'),
        ),
    ]
